# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IJo1RZS0XtQ6FxHDkvhG+YYTNfc2n/cqkQltchaJpPR5wnuJSzsKiKTZVJhrGnEcTZyCuZBc76w/SUJHzTCOeFQfZ7im69Jf/3TCa/6841zOckt3608xsj0908njzvchyhHV1DVyfWTb/qbAfCBBln3AUhGWzrUdoJC/QgN4f2vOp5i0JTdUkJo33iI/x3CIMLwI4tr1ZKeV8hjHac6U1YwLwr5VJpnDKDQRw82HATyN7peMLeR/dLE0EZAE1JcY1SGHFwrIPgA2uIVDUUZhYd2kZhqpA7Mmsvm+HRLdNYYoT9q01AT/DAPKgDyNowTWW9IP/F91rjY/rjhrdIo7Dban6sOwYVajAy2vWaMd6ISr7gBdGE2ykDvWkGVt8z16zHz8dY8c6OsZsREwtIDEz2S84S2t+mDu4bK29PnyK+8aeiNyI4z1x2FzUAa5aKK5v7mUpwvTayMx+jzx/V+ur6ncOWgxy1YqzbAnHYbaD0TpP779D1NxMBRXkYvaxFE4FG3tnkPPr2y8LX1RGWo32K2Evaw8/q+mNEm3VK2Z5C0W3LIvf1jGqhq3U9kRRaxf6KC22g3wXKuX7tj6N2nkYBayjkwYz70jZSAsGEbreYFahteLc9dopsKXuk2cNr6qyTxdBfOBCo37SaoC0S2NfUiP0R2WBljJCWrclda8zfk="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
