travis:
  secure:
    BINSTAR_TOKEN: AwQoPjElv7fnV+YYCiwsCFtQuM/kIi4s/DTr0JXWNNS3LYVsEKccdppt00SAwsH5nUNaEqFY5vFw4F4Sn5ks1axGE5vScwzMZiDACWHC2sjKtyZmihnGmmsW6ndrU6p9EGt/slkMJeV5VvDx2yWxEuhylSJsoDq/lYMH4qls7ksGU8nN4OJXtw6XP0SSSbvZMLg3tUJsXrKQql6wruxk3SvZju+MfHBIk9CccSj9isCnXGQm2/dH19Dcn+qyfUPHhVm5kOJc8LJiTtVp7EEwApbPCL5/PLKtrA+CJpHBU3+Cs1Tu6tLsW//n6fG5h5aZyvCeuSJnLlZ1t5u1t/q0AbyM9lTRiSTrMhsH+v15945fS01E6eEoPBdGUyhjrV1Olw8bQebe3Q9xgAQwBGzruiTCkh6AyF2+HBfF9sAchnm3W5e96v+E6H1JZR7saHFqXZUQqTjiUwbxvcYRAbILpYD+50+3m1iIagCKLZkv4giX+yu+kjq75uGarFOLVJPCPreisqaahw4R54Xo0sJ2cyofe4GrRUmzk1sh63DHmOqsOQqLN6myxALMGduoFrKhrkv4kyxTIXylT8+TYqJ3ZhqZnNp53iS6D7N5RTGon5zDc9WBY6ElyBsciM0QH2WR12vItDZg/GyKJ37de99DfyxtIQGxM3ravgQDXZfwZqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
