travis:
  secure:
    BINSTAR_TOKEN: IJo1RZS0XtQ6FxHDkvhG+YYTNfc2n/cqkQltchaJpPR5wnuJSzsKiKTZVJhrGnEcTZyCuZBc76w/SUJHzTCOeFQfZ7im69Jf/3TCa/6841zOckt3608xsj0908njzvchyhHV1DVyfWTb/qbAfCBBln3AUhGWzrUdoJC/QgN4f2vOp5i0JTdUkJo33iI/x3CIMLwI4tr1ZKeV8hjHac6U1YwLwr5VJpnDKDQRw82HATyN7peMLeR/dLE0EZAE1JcY1SGHFwrIPgA2uIVDUUZhYd2kZhqpA7Mmsvm+HRLdNYYoT9q01AT/DAPKgDyNowTWW9IP/F91rjY/rjhrdIo7Dban6sOwYVajAy2vWaMd6ISr7gBdGE2ykDvWkGVt8z16zHz8dY8c6OsZsREwtIDEz2S84S2t+mDu4bK29PnyK+8aeiNyI4z1x2FzUAa5aKK5v7mUpwvTayMx+jzx/V+ur6ncOWgxy1YqzbAnHYbaD0TpP779D1NxMBRXkYvaxFE4FG3tnkPPr2y8LX1RGWo32K2Evaw8/q+mNEm3VK2Z5C0W3LIvf1jGqhq3U9kRRaxf6KC22g3wXKuX7tj6N2nkYBayjkwYz70jZSAsGEbreYFahteLc9dopsKXuk2cNr6qyTxdBfOBCo37SaoC0S2NfUiP0R2WBljJCWrclda8zfk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
